### ISSUE TITLE
Can´t really get it to work! :/

### ISSUE THREAD

**Issue by MaistroX** [drops76/SRT-Cleaner#1]
I run Windows 10 Pro 64 and can´t seem to get the script to be integrated to explorer's contextual menu.
EXACLY, step by step do I need to do to get it to work?
Ex: Say my folder is placed under "C:\SRT-Cleaner-master"
Tryed to edit  with "SRTcleaner.reg"

"Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\srt_auto_file\shell\SRT Cleaner]

[HKEY_CLASSES_ROOT\srt_auto_file\shell\SRT Cleaner\command]
@="powershell & \"C:\\SRT-Cleaner-master\\SRTcleaner.ps1\" %1""

did not work! :(

Please help!

Regards MaistroX

**Comment by drops76** [comment]
Hi, yes I had similar problem on Windows 10. I resolved it by creating a send to shortcut, here are details:

1. First make sure that you have enabled powershell scripts execution: open command line as Administrator and type:
`powershell Set-ExecutionPolicy RemoteSigned`
(it's one time operation)

2. Open Windows Explorer and type in address bar: `shell:sendTo` to open your sendTo folder.

3. Create a new shortcut and as a destination target type:
`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -File C:\your\path\to\SRT-Cleaner-master\SRTcleaner.ps1`, then as a name type your desired action name (ie: SRT Cleaner).

That's all. Now you can right click your .srt file and select Send To, then your action. The file will be cleaned.

Let me know if that's works for you.

**Comment by MaistroX** [comment]
That worked BUT making a test.srt file with this for text inside-> 
"<i>tjolla hopp</i>
<b>"
Doesnt Clean the srt file, it´s all the same after a run. :/

**Comment by drops76** [comment]
I don't see here any special characters to clean in this example, is it `<i>` and `</i>` ?

**Comment by MaistroX** [comment]
The < > and so on are in that info, but did not show here in my answer, just so you don´t Think I have missed what should be replaced ;)

**Comment by drops76** [comment]
So it should work. Paste as a code sample from your srt file (it's in backticks -> ` at start and end so it won't apply formatting here).

**Comment by MaistroX** [comment]
My bad, via powershell promt it does Clean the file, it´s with my Send To it does´nt.

**Comment by MaistroX** [comment]
And this is in Powershell the command: "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -File C:\SRT-Cleaner-master\SRTcleaner.ps1 C:\SRT-Cleaner-master\Test.srt"
And this line is in the shortcut made in "shell:sendTo" folder
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -File C:\SRT-Cleaner-master\SRTcleaner.ps1"
And the later does not Clean the file.

**Comment by drops76** [comment]
strange.
Try to add at the end of SRTcleaner.ps1 file:
`Read-Host -Prompt "Press Enter to exit"`
so we can check if there are any errors in console.

**Comment by MaistroX** [comment]
IF I add like this>. 
`$filename = $($args[0])
(Get-Content -literalPath $filename).replace('<i>','').replace('</i>','').replace('<b>','').replace('</b>','') -replace'(\{[\s\S]*)}',''| Set-Content -literalPath $filename Read-Host -Prompt "Press Enter to exit"`

It´s still the same, opens powershell fast the Close it, nothing happens.

**Comment by drops76** [comment]
Add it in new line not at the end of last commad.

**Comment by MaistroX** [comment]
ok, added it like this insted:

$filename = $($args[0])
(Get-Content -literalPath $filename).replace('<i>','').replace('</i>','').replace('<b>','').replace('</b>','') -replace'(\{[\s\S]*)}',''| Set-Content -literalPath $filename
Read-Host -Prompt "Press Enter to exit"

Same thing, opens fast the Closes.

**Comment by drops76** [comment]
It looks like the script is not running at all from Send To shortcut.
Did you enabled script execution by typing `powershell Set-ExecutionPolicy RemoteSigned` in command line **as administrator** ?

**Comment by MaistroX** [comment]
Yes, it was the first thing I did Before trying anything else.
Did it once more after read the last psot here again.

**Comment by MaistroX** [comment]
Just chekced via this:
"
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine    RemoteSigned
"

**Comment by MaistroX** [comment]
With a few Changes I managed to get a powershell screen that stays on top but does´nt Clean the nfo.
Here´s the screen:
"
Set-Content : Åtkomst till sökvägen F:\On***********.srt nekas.
At C:\SRT-Cleaner-master\SRTcleaner.ps1:2 char:139
+ ... b>','') -replace'(\{[\s\S]*)}',''| Set-Content -literalPath $filename
+                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-Content], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.SetContentCommand

Press Enter to exit:"

"nekas" = denied

**Comment by drops76** [comment]
It looks like it's problem with file permissions. The srt file is read-only? Maybe F drive is mounted as read-only?
Try to put this file to your documents folder. I personally use it on network drives and it works without any problems.
I can't figure anything else here.

**Comment by MaistroX** [comment]
Thx, that was it, all nfo:s was read only, changed it and worked great. :)

**Comment by drops76** [comment]
Great, 
does it work from send to also?

**Comment by MaistroX** [comment]
And also, IS IT POSSIBLE to have the SRT Cleaner added to the first right click screen isnted of the more complicated one with the Open With, like this Ex: https://ibb.co/bEY7a0 ? :)

**Comment by drops76** [comment]
Currently it works for one file only. But this is a good idea to make it better and iterate all args...

Open with... worked initially, before Windows 10 (the regfile did it).
I don't know why it's not working with Windows 10, so I did this workaround some time ago and forget to update code here.

**Comment by MaistroX** [comment]
Just an ide:a, make an install.exe with right permissions and able to add it to the first menu that show up on right-click, also have a editable *.ini file were one can more argumets that needs cleansed from nfo:s, that one would be Amazing! :)
I would more then happy to help you test and come with suggestions IF you´re up for it!? 
My mail: vipps75@gmail.com

**Comment by drops76** [comment]
I didn't want to make a whole application for 2-line script :) But maybe some time I'll do it. 
Now it's time to make it aware of more than one file first.

**Comment by drops76** [comment]
Just updated the ps file. Now it accepts all files and process them all one by one.

**Comment by MaistroX** [comment]
Multiple nfo:s works Perfect now! :)

**Comment by MaistroX** [comment]
How to edit SRTcleaner.ps1 so `♪  ` does´nt become `? ` ?
Coz somethings you want left. :)

**Comment by MaistroX** [comment]
But I don´t want the keynotes of course to be replaced by anything. :)

**Comment by MaistroX** [comment]
Since SRTcleaner.ps1 Changes stuff it should not do!
HOW should the SRTcleaner.ps1 look to ONLY Clean out: `</i> , <i> , </b> & <b>`?
Sice all special caracters need to be there since this is a subtilte format and should allways be able to hold the, allso be saved as Unicode (UTF-8) even IF it was a ANSI first! :)

**Comment by MaistroX** [comment]
All `.replace('♪','')` did was to remove `♪`  , not keep them and replace them with space.
Original SRTcleaner.ps1 does allso remove `♪` BUT Exchange them with a "?"! :(

**Comment by drops76** [comment]
Ok, I see your files are encoded in UTF-8 .
In that case simply update this part of script to be like this: `Set-Content -Encoding UTF8 -literalPath $filename`

It will however affect ANSI files to be UTF-8 encoded with signature, so I will look for better solution, but not today :)
